name: Github Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0' # Every Sunday at 6:15 UTC
  workflow_dispatch: # Manual trigger
    inputs:
      environment:
        type: environment
        required: true
    
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Output event name
        run: |
            echo "Event: '${{ github.event_name }}"

      - name: Output branch name
        run:  |
            echo "Branch: '${{ github.ref }}"

      - name: List files in repository
        run: |
          ls -R
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: demo-job
    environment: Test
    steps:
      - run: echo "Testing..."
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: demo-job
    environment: Load-Test
    steps:
      - run: |
          echo "Testing..."
          sleep 15
  Production:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'Production'
    needs: [Test, Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
          echo "Step 1..."
          sleep 1
      - run: |
          echo "Step 2..."
          sleep 1
      - run: |
          echo "Step 3..."
          sleep 1
          
