name: Hello World CI

on:
  push:
    branches: [ main ]
    paths:
      - 'hello-world-docker-action/**'
  workflow_dispatch: # Manual trigger

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run container
        id: hello-action
        uses: ./hello-world-docker-action
        env: 
          INPUT_WHO_TO_GREET: 'test-name'
      
      - name: Output the time
        run: |
          echo "Time = ${{ steps.hello-action.outputs.time }}"
