name: Reuse other flow

on:
  - workflow_dispatch
  
jobs: 
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "Someone"

  use-output:
    runs-on: ubuntu-latest
    needs: 
      - call-workflow
    steps:
      - run: |
            echo "Time of greeting: ${{needs.call-workflow.outputs.current-time}}"
    
